<?php

namespace Database\Seeders;

use App\Models\LaunchService;
use Illuminate\Database\Seeder;

class LaunchSeeder extends Seeder
{
    public function run(): void
    {
        LaunchService::query()
            ->whereIn('name', ['Bhola-Barishal Launch Service', 'Bhola-Dhaka Night Launch'])
            ->update(['status' => 'inactive']);

        $elishaWarning = 'Schedule may change due to weather, river condition, Eid special service or authority instruction. Latest disruption note: UNB reported on 28 Jul 2026 that Elisha launch/ferry terminals were damaged and services were suspended; confirm with terminal or hotline before travel.';
        $weatherWarning = 'Route verified from BIWTA/BSS/news route lists. Time can change frequently due to tide, weather, vessel fitness and authority instruction; confirm locally before travel.';

        $commonDhakaIlisha = [
            'operator_name' => 'Dhaka-Ilisha passenger launch service',
            'route_from' => 'Dhaka',
            'route_to' => 'Ilisha, Bhola',
            'departure_terminal' => 'Dhaka Sadarghat / approved Dhaka terminal',
            'arrival_terminal' => 'Ilisha Launch Terminal, Bhola',
            'running_days' => 'Daily, subject to weather and BIWTA instruction',
            'has_cabin' => true,
            'has_ac' => false,
            'has_food' => true,
            'online_booking' => false,
            'district' => 'Bhola',
            'upazila' => 'Bhola Sadar',
            'address' => 'Ilisha Launch Terminal, Bhola',
            'description' => 'Published Dhaka to Ilisha passenger launch schedule. Passengers should reach the terminal early and confirm the latest time before travel.',
            'notes' => 'Source: Bholabani, 28 Jun 2026; public Facebook schedule snippets also show similar Dhaka-Ilisha timing. ' . $elishaWarning,
            'status' => 'active',
        ];

        $commonIlishaDhaka = [
            'operator_name' => 'Ilisha-Dhaka passenger launch service',
            'route_from' => 'Ilisha, Bhola',
            'route_to' => 'Dhaka',
            'departure_terminal' => 'Ilisha Launch Terminal, Bhola',
            'arrival_terminal' => 'Dhaka Sadarghat / approved Dhaka terminal',
            'running_days' => 'Daily, subject to weather and BIWTA instruction',
            'has_cabin' => true,
            'has_ac' => false,
            'has_food' => true,
            'online_booking' => false,
            'district' => 'Bhola',
            'upazila' => 'Bhola Sadar',
            'address' => 'Ilisha Launch Terminal, Bhola',
            'description' => 'Published Ilisha to Dhaka passenger launch schedule. Passengers should reach the terminal early and confirm the latest time before travel.',
            'notes' => 'Source: Bholabani, 28 Jun 2026. ' . $elishaWarning,
            'status' => 'active',
        ];

        $commonCharfashionDhaka = [
            'operator_name' => 'Dhaka-Charfashion passenger launch service',
            'route_from' => 'Dhaka',
            'route_to' => 'Charfashion, Bhola',
            'departure_terminal' => 'Dhaka Sadarghat Launch Terminal',
            'arrival_terminal' => 'Charfashion / Betua / Ghosher Hat terminal area',
            'running_days' => 'Regular, confirm before travel',
            'has_cabin' => true,
            'has_ac' => true,
            'has_food' => true,
            'online_booking' => false,
            'district' => 'Bhola',
            'upazila' => 'Charfashion',
            'address' => 'Charfashion, Bhola',
            'description' => 'Dhaka to Charfashion passenger launch service.',
            'notes' => 'Sources: multiple public 2025/2026 schedule posts list Farhan-5, Karnaphuli-12 and Tasrif-4 for Dhaka-Charfashion. Confirm latest schedule before travel.',
            'status' => 'active',
        ];

        $launches = [
            ['name' => 'Doel Pakhi-10', 'departure_time' => '07:30', ...$commonDhakaIlisha],
            ['name' => 'Doel Pakhi-8', 'departure_time' => '08:00', ...$commonDhakaIlisha],
            ['name' => 'Karnaphuli-14', 'departure_time' => '09:00', ...$commonDhakaIlisha],
            ['name' => 'Farhan-9', 'departure_time' => '11:45', ...$commonDhakaIlisha],
            ['name' => 'Surabhi-8 / Al Walid-4', 'departure_time' => '14:00', ...$commonDhakaIlisha],
            ['name' => 'Sampad / Karnaphuli-3', 'departure_time' => '16:00', ...$commonDhakaIlisha],
            ['name' => 'Farhan-3/4 or Tasrif-1/2', 'departure_time' => '18:30', ...$commonDhakaIlisha],
            ['name' => 'Rajarhat-B / Karnaphuli-11', 'departure_time' => '22:00', ...$commonDhakaIlisha],
            ['name' => 'Asa-Jawa-2 / Pubali-5', 'departure_time' => '23:00', ...$commonDhakaIlisha],

            ['name' => 'Asa-Jawa-2 / Pubali-5', 'departure_time' => '07:30', ...$commonIlishaDhaka],
            ['name' => 'Sampad / Karnaphuli-3', 'departure_time' => '08:40', ...$commonIlishaDhaka],
            ['name' => 'Karnaphuli-11 / Rajarhat-B', 'departure_time' => '09:40', ...$commonIlishaDhaka],
            ['name' => 'Doel Pakhi-10', 'departure_time' => '14:00', ...$commonIlishaDhaka],
            ['name' => 'Karnaphuli-14', 'departure_time' => '15:10', ...$commonIlishaDhaka],
            ['name' => 'Doel Pakhi-8', 'departure_time' => '19:45', ...$commonIlishaDhaka],
            ['name' => 'Farhan-9', 'departure_time' => '21:50', ...$commonIlishaDhaka],
            ['name' => 'Surabhi-8 / Al Walid-4', 'departure_time' => '22:20', ...$commonIlishaDhaka],

            ['name' => 'MV Farhan-5', 'departure_time' => '19:00', 'arrival_time' => '07:00', ...$commonCharfashionDhaka],
            ['name' => 'MV Karnaphuli-12', 'departure_time' => '19:00', 'arrival_time' => '07:00', ...$commonCharfashionDhaka],
            ['name' => 'MV Tasrif-4', 'departure_time' => '20:30', 'arrival_time' => '06:00', ...$commonCharfashionDhaka],

            [
                'name' => 'Ramnewaz-Dhaka Launch',
                'operator_name' => 'Monpura-Dhaka passenger launch service',
                'route_from' => 'Ramnewaz Launch Ghat, Monpura',
                'route_to' => 'Dhaka',
                'departure_terminal' => 'Ramnewaz Launch Ghat, Monpura',
                'arrival_terminal' => 'Dhaka Sadarghat Launch Terminal',
                'departure_time' => '14:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Ramnewaz Launch Ghat, Monpura, Bhola',
                'description' => 'Direct Monpura to Dhaka launch service from Ramnewaz launch ghat.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Dhaka-Monpura Launch',
                'operator_name' => 'Dhaka-Monpura passenger launch service',
                'route_from' => 'Dhaka',
                'route_to' => 'Monpura, Bhola',
                'departure_terminal' => 'Dhaka Sadarghat Launch Terminal',
                'arrival_terminal' => 'Monpura / Ramnewaz Launch Ghat',
                'departure_time' => '17:00',
                'arrival_time' => '07:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Monpura, Bhola',
                'description' => 'Direct Dhaka to Monpura launch service.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Hajirhat-Tazumuddin Sea Truck',
                'operator_name' => 'Monpura-Tazumuddin sea-truck service',
                'route_from' => 'Hajirhat Launch Ghat, Monpura',
                'route_to' => 'Tazumuddin, Bhola',
                'departure_terminal' => 'Hajirhat Launch Ghat',
                'arrival_terminal' => 'Tazumuddin Sea-Truck Terminal',
                'departure_time' => '10:00',
                'running_days' => 'Daily when vessel is operational',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Hajirhat Launch Ghat, Monpura, Bhola',
                'description' => 'Sea-truck service from Monpura Hajirhat to Tazumuddin.',
                'notes' => 'Source: Monpura upazila government page. Latest news in Jul 2026 reported Monpura sea-truck service disruption; confirm before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Ramnewaz-Tazumuddin Sea Truck',
                'operator_name' => 'Monpura-Tazumuddin sea-truck service',
                'route_from' => 'Ramnewaz Launch Ghat, Monpura',
                'route_to' => 'Tazumuddin, Bhola',
                'departure_terminal' => 'Ramnewaz Launch Ghat',
                'arrival_terminal' => 'Tazumuddin Sea-Truck Terminal',
                'departure_time' => '11:00',
                'running_days' => 'Daily when vessel is operational',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Ramnewaz Launch Ghat, Monpura, Bhola',
                'description' => 'Sea-truck service from Monpura Ramnewaz to Tazumuddin.',
                'notes' => 'Source: Monpura upazila government page. Latest news in Jul 2026 reported Monpura sea-truck service disruption; confirm before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Tazumuddin-Monpura Sea Truck',
                'operator_name' => 'Tazumuddin-Monpura sea-truck service',
                'route_from' => 'Tazumuddin, Bhola',
                'route_to' => 'Monpura, Bhola',
                'departure_terminal' => 'Tazumuddin Sea-Truck Terminal',
                'arrival_terminal' => 'Monpura Launch Ghat',
                'departure_time' => '15:00',
                'running_days' => 'Daily when vessel is operational',
                'district' => 'Bhola',
                'upazila' => 'Tazumuddin',
                'address' => 'Tazumuddin Sea-Truck Terminal, Bhola',
                'description' => 'Sea-truck service from Tazumuddin to Monpura.',
                'notes' => 'Source: Monpura upazila government page. Latest news in Jul 2026 reported Monpura sea-truck service disruption; confirm before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Jonota Ghat-Charfashion Launch',
                'operator_name' => 'Sakuchia-Charfashion local launch service',
                'route_from' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'route_to' => 'Charfashion, Bhola',
                'departure_terminal' => 'Jonota Launch Ghat, Sakuchia',
                'arrival_terminal' => 'Charfashion / Betua Launch Ghat',
                'departure_time' => '09:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'description' => 'Local launch service from Sakuchia Jonota ghat to Charfashion.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Jonota Ghat-Charfashion Launch',
                'operator_name' => 'Sakuchia-Charfashion local launch service',
                'route_from' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'route_to' => 'Charfashion, Bhola',
                'departure_terminal' => 'Jonota Launch Ghat, Sakuchia',
                'arrival_terminal' => 'Charfashion / Betua Launch Ghat',
                'departure_time' => '14:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Monpura',
                'address' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'description' => 'Local launch service from Sakuchia Jonota ghat to Charfashion.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Betua-Jonota Ghat Launch',
                'operator_name' => 'Betua-Monpura local launch service',
                'route_from' => 'Betua Ghat, Charfashion',
                'route_to' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'departure_terminal' => 'Betua Ghat',
                'arrival_terminal' => 'Jonota Launch Ghat, Sakuchia',
                'departure_time' => '10:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Charfashion',
                'address' => 'Betua Ghat, Charfashion, Bhola',
                'description' => 'Local launch service from Betua to Monpura Jonota ghat.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Betua-Jonota Ghat Launch',
                'operator_name' => 'Betua-Monpura local launch service',
                'route_from' => 'Betua Ghat, Charfashion',
                'route_to' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'departure_terminal' => 'Betua Ghat',
                'arrival_terminal' => 'Jonota Launch Ghat, Sakuchia',
                'departure_time' => '12:30',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Charfashion',
                'address' => 'Betua Ghat, Charfashion, Bhola',
                'description' => 'Local launch service from Betua to Monpura Jonota ghat.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
            [
                'name' => 'Betua-Jonota Ghat Launch',
                'operator_name' => 'Betua-Monpura local launch service',
                'route_from' => 'Betua Ghat, Charfashion',
                'route_to' => 'Jonota Launch Ghat, Sakuchia, Monpura',
                'departure_terminal' => 'Betua Ghat',
                'arrival_terminal' => 'Jonota Launch Ghat, Sakuchia',
                'departure_time' => '15:00',
                'running_days' => 'Daily, according to Monpura upazila portal',
                'district' => 'Bhola',
                'upazila' => 'Charfashion',
                'address' => 'Betua Ghat, Charfashion, Bhola',
                'description' => 'Local launch service from Betua to Monpura Jonota ghat.',
                'notes' => 'Source: Monpura upazila government communication page. Confirm latest time before travel.',
                'status' => 'active',
            ],
        ];

        $routeOnly = [
            ['Ilisha-Maju Chowdhury/Lakshmipur Launch-Sea Truck Route', 'Ilisha, Bhola', 'Maju Chowdhury Ghat, Lakshmipur', 'Bhola Sadar'],
            ['Ilisha-Mehendiganj Launch Route', 'Ilisha, Bhola', 'Mehendiganj, Barishal', 'Bhola Sadar'],
            ['Bhola-Baufal Launch Route', 'Bhola', 'Baufal, Patuakhali', 'Bhola Sadar'],
            ['Lalmohan-Nazirpur Launch Route', 'Lalmohan, Bhola', 'Nazirpur', 'Lalmohan'],
            ['Daulatkhan-Alexander Launch Route', 'Daulatkhan, Bhola', 'Alexander, Lakshmipur', 'Daulatkhan'],
            ['Mirzakalu-Alexander Launch Route', 'Mirzakalu, Bhola', 'Alexander, Lakshmipur', 'Bhola'],
            ['Tajumuddin-Monpura Launch-Sea Truck Route', 'Tajumuddin, Bhola', 'Monpura, Bhola', 'Tajumuddin'],
            ['Monpura-Hatia Launch Route', 'Monpura, Bhola', 'Hatia, Noakhali', 'Monpura'],
            ['Hatia-Dhaka Launch Route', 'Hatia, Noakhali', 'Dhaka', 'Monpura'],
            ['Hatia-Charfashion Launch Route', 'Hatia, Noakhali', 'Charfashion, Bhola', 'Charfashion'],
            ['Charfashion-Monpura Launch Route', 'Charfashion, Bhola', 'Monpura, Bhola', 'Charfashion'],
            ['Betua-Monpura Launch Route', 'Betua, Charfashion', 'Monpura, Bhola', 'Charfashion'],
            ['Monpura-Dhaka Launch Route', 'Monpura, Bhola', 'Dhaka', 'Monpura'],
            ['Charfashion-Dhaka Launch Route', 'Charfashion, Bhola', 'Dhaka', 'Charfashion'],
            ['Ghosher Hat-Dhaka Launch Route', 'Ghosher Hat, Charfashion', 'Dhaka', 'Charfashion'],
            ['Hakimuddin-Dhaka Launch Route', 'Hakimuddin, Borhanuddin', 'Dhaka', 'Borhanuddin'],
            ['Borhanuddin-Dhaka Launch Route', 'Borhanuddin, Bhola', 'Dhaka', 'Borhanuddin'],
            ['Lalmohan-Dhaka Launch Route', 'Lalmohan, Bhola', 'Dhaka', 'Lalmohan'],
            ['Bhola Sadar Kheyaghat-Dhaka Launch Route', 'Bhola Sadar Kheyaghat', 'Dhaka', 'Bhola Sadar'],
            ['Bhola-Dhaka Launch Route', 'Bhola', 'Dhaka', 'Bhola Sadar'],
            ['Bhola-Barishal Launch Route', 'Bhola', 'Barishal', 'Bhola Sadar'],
            ['Bheduria-Laharhat Launch/Ferry Route', 'Bheduria Ghat, Bhola', 'Laharhat, Barishal', 'Bhola Sadar'],
            ['Kachchhpia-Dhalchar Launch Route', 'Kachchhpia, Charfashion', 'Dhalchar, Charfashion', 'Charfashion'],
            ['Kachchia-Kukri Mukri Launch Route', 'Kachchia, Charfashion', 'Kukri Mukri, Charfashion', 'Charfashion'],
            ['Kachchia-Char Patila Launch Route', 'Kachchia, Charfashion', 'Char Patila', 'Charfashion'],
            ['Abubakarpur-Dashmina Launch Route', 'Abubakarpur, Bhola', 'Dashmina, Patuakhali', 'Bhola'],
            ['Tulatuli-Majher Char Launch Route', 'Tulatuli, Bhola Sadar', 'Majher Char', 'Bhola Sadar'],
            ['Elisha-Ramdaspur Launch Route', 'Elisha, Bhola', 'Ramdaspur', 'Bhola Sadar'],
            ['Nasir Majhi-Char Madanpur Launch Route', 'Nasir Majhi, Bhola Sadar', 'Char Madanpur, Daulatkhan', 'Bhola Sadar'],
            ['Tajumuddin-Char Jahiruddin Launch Route', 'Tajumuddin, Bhola', 'Char Jahiruddin', 'Tajumuddin'],
            ['Hakimuddin-Monpura-Char Jahiruddin Launch Route', 'Hakimuddin, Borhanuddin', 'Monpura / Char Jahiruddin', 'Borhanuddin'],
            ['Bhola-Monpura-Hakimuddin Launch Route', 'Bhola', 'Monpura / Hakimuddin', 'Bhola'],
            ['Bhola-Lakshmipur-Charfashion-Monpura Route', 'Bhola', 'Lakshmipur / Charfashion / Monpura', 'Bhola'],
        ];

        foreach ($routeOnly as [$name, $from, $to, $upazila]) {
            $launches[] = [
                'name' => $name,
                'operator_name' => 'Bhola internal river route service',
                'route_from' => $from,
                'route_to' => $to,
                'departure_terminal' => $from,
                'arrival_terminal' => $to,
                'departure_time' => null,
                'running_days' => 'Regular route; schedule must be confirmed locally',
                'has_cabin' => false,
                'has_ac' => false,
                'has_food' => false,
                'online_booking' => false,
                'district' => 'Bhola',
                'upazila' => $upazila,
                'address' => $from,
                'description' => 'Verified Bhola district inland water route. Exact vessel name, fare and daily timing should be updated by admin or local users when confirmed.',
                'notes' => 'Sources: BSS route list dated 30 Jul 2025 and 3 Sep 2025; Observer/BDNews24/Dhaka Tribune reports for active/suspended route mentions. ' . $weatherWarning,
                'status' => 'active',
            ];
        }

        foreach ($launches as $launch) {
            LaunchService::query()->updateOrCreate(
                [
                    'name' => $launch['name'],
                    'route_from' => $launch['route_from'],
                    'route_to' => $launch['route_to'],
                    'departure_time' => $launch['departure_time'],
                ],
                $launch
            );
        }
    }
}